
import "./globals.css";
import { Inter } from "next/font/google";
import ToasterContext from "./context/ToasterContext";
import NavBar from "./components/NavBar";
import  { AuthProvider }  from '../app/context/AuthContext';


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "SmartOwl",
  // description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <ToasterContext />
          <NavBar/>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
